<li class="span4">
	<label for="f_<?=$weapon['nom']?>">
		<input  id="f_<?=$weapon['nom']?>" type="radio" name="f_<?=$weapon['type']?>" value="<?=$weapon['id_weapon']?>" required class="radio-arme" />
		<img class="pictogramme <?=$weapon['class']?>" src="sources/img/arme/<?=$weapon['nom']?>.png" alt="<?=$weapon['nom']?>">
	</label>
	<div class="definition">
		<img src="sources/img/arrow_up.png" alt="arrow"><?=$weapon['class']?>
	</div>
</li>
