<div id="container" class="container">
	<div class="span12">
		<p class="infosfooter">
			<?=$titre_application?><br />
			Development Team : 
				<?=$developpeur1?>, 
				<?=$developpeur2?> (<a href="http://<?=$developpeur2_site?>" target="_blank" title="Visitez son site"><?=$developpeur2_site_name?></a>), 
				<?=$developpeur3?> (<a href="http://<?=$developpeur3_site?>" target="_blank" title="Visitez son site"><?=$developpeur3_site_name?></a>), 
				<?=$developpeur4?><br />
			&copy;2014 - <?=$compagnie_promo?> (<a href="http://<?=$compagnie_site?>" target="_blank" title="Visitez le site de <?=$compagnie_name?> "><?=$compagnie_site_name?></a>)
		</p>
	</div>
</div>