<div class="row-fluid">
	<figure class="span6 offset4">
		<img class="span3" src="sources/img/enemy/<?=$winner['arme']?>.png" alt="<?=$winner['arme']?>">
		<ficaption class="span8">		
			<p><i class="fa fa-quote-left fa-1x"></i> La plus grande victoire c'est peut-être d'admettre ta défaite.<i class="fa fa-quote-right fa-1x"></i></p>
			<cite><h3><?=$winner['nom']?></h3></cite>
		</ficaption>
	</figure>		
</div>