<form action="index.php?page=content" method="POST">
	<div class="row">	
		<div class="container span3">	
			<legend>Choix de votre Arme </legend>
			<ul class="inline unstyled arme">
				<?php require('apps/armes.php'); ?>
			</ul>	
		</div>
		
		<div class="container span3">
			<legend>Choix de votre Potion</legend>
			<ul class="inline unstyled potion">
				<?php require('apps/potion.php'); ?>
			</ul>
		</div>
		
		<div class="container span3">
			<legend>Choix de votre Sort</legend>
			<ul class="inline unstyled sort">
				<?php require('apps/sort.php'); ?>
			</ul>
		</div>
	</div>

	<div class="span6 offset3 play">
		<input class="span3 btn btn-success" type="submit" name='play' value='JOUER'>
	</div>

</form>