<li class="span6">
	<label for="f_<?=$weapon['nom']?>">
		<input id="f_<?=$weapon['nom']?>" type="radio" name="f_<?=$weapon['type']?>" value="<?=$weapon['id_weapon']?>">
		<img class="pictogramme <?=$weapon['class']?>" src="sources/img/sort/<?=$weapon['nom']?>.png" alt="<?=$weapon['nom']?>">
	</label>
	<div class="definition">
		<img src="sources/img/arrow_up.png" alt="arrow"><?=$weapon['class']?>
	</div>
</li>