<div id="container" class="container">
	<div class="div-center">
		<form action="index.php?page=user.login" method="POST" id="formcnx" class="form-horizontal formcnx">
			<h2 class="titre-form" id="titreform">Connexion</h2>
			<div class="control-group" style="margin:2px">
				<label for="pseudo" class="control-label connexion" style="width: 100px">Joueur</label>
				<div class="controls" style="margin-left: 120px;">
					<input id="pseudo" type="text" placeholder="Votre pseudo&hellip;" name="f_joueur" value="<?= $joueur?>" />
				</div>
			</div>
			<div class="control-group" style="margin:2px">
				<label for="password" class="control-label connexion" style="width: 100px">Mot de passe</label>
				<div class="controls" style="margin-left: 120px;">
					<input id="password" type="password" placeholder="Mot de passe" name="f_password" value=""/>
				</div>
			</div>
			<div id="useremail" class="control-group" style="margin:2px">
				<label for="email" class="control-label connexion" style="width: 100px">Email</label>
				<div class="controls" style="margin-left: 120px;">
					<input type="email" placeholder="email" name="f_email"/>
					<?= $error;?>
				</div>
			</div>
			<div class="control-group">
				<div class="controls" style="margin: 6px 0px 0px 298px; padding-bottom: 2px;">
					<input type="submit" name="f_btn_connexion" value="Connexion" />
				</div>
			</div>
		</form>
	</div>
</div>

<?php
	if(!isset($_GET["page"]))
	{
		$_GET["page"] = "";
	}
	if($_GET["page"]=="user.login"){
		?>
		<script>
			//alert();
			//$("body").html("TEST");
			$("#useremail").css("display","inline-block");
		</script>
<?php
	}
?>