<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title><?=$titre_application?></title>
		
		<!-- Styles -->
		<link rel="stylesheet" href="sources/css/reset.css">
	    <link rel="stylesheet" href="sources/css/bootstrap.css">
	    <link rel="stylesheet" href="sources/css/bootstrap-responsive.css">
	    <link rel="stylesheet" href="sources/css/animate.css">
	    <link rel="stylesheet" href="sources/css/font-awesome.css">
    	<link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="sources/css/tux_battle_style.css">
		
		<!-- Scripts -->
		<script src="sources/js/jquery.js"></script>
		<script src="sources/js/bootstrap.js"></script>
	</head>

	<body>
	
